apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/spudopenai
    newTag: 75ce5e27da1be36869ac963069b57e7b96687e1b
