apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/spudopenai
    newTag: a0f8153f8b44b0e405f111c98e88bfaa45e3f2c8
